[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.7.1", features = ["csr"] }
thaw = { version = "0.4.0-rc", features = ["csr"] }
